version: '3.7'
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    hostname: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - bookstore
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    hostname: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/rules.yml:/etc/prometheus/rules.yml
      - ./prometheus:/prometheus
    networks:
      - bookstore
  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - bookstore

networks:
  bookstore:
    name: bookstore
