create table User_Payment_Customer (
    id varchar(255) not null,
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    payment_customer_id varchar(255) not null,
    user_id varchar(255) not null,
    primary key (id)
);

create table User_Payment_Customer_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    payment_customer_id varchar(255),
    user_id varchar(255),
    primary key (id, REV)
);

create table REVINFO (
    REV integer generated by default as identity,
    REVTSTMP bigint,
    primary key (REV)
);

alter table User_Payment_Customer_AUD
   add constraint FK9l0v0ri48bqymf6556flo9ock
   foreign key (REV)
   references REVINFO;

alter table User_Payment_Customer
   add constraint UK_pold9y56wy4qxkuc4dbd40dt7 unique (payment_customer_id);

alter table User_Payment_Customer
   add constraint UK_tc9yscgisqsno5i35hqacufmf unique (user_id);
