#Common actuator endpoint related configuration
management:
  endpoints:
    web:
      base-path: /actuator
      exposure.include: health, info, prometheus
      path-mapping.prometheus: metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      cache:
        time-to-live: 1ms

#Common Spring Boot related configuration
spring:
  main:
    banner-mode: OFF

#Common Spring Cloud related configuration
  cloud:
    consul:
      discovery:
        #To generate unique instance id for each service in Consul
        instance-id: ${spring.application.name}:${random.int[1,999999]}
    loadbalancer:
      ribbon:
        #To use Spring Cloud Load Balancer instead of Ribbon, which should be required in the classpath
        enabled: false
  #Spring cloud Sleuth related configuration
  sleuth:
    sampler:
      probability: 1
  #Spring cloud Zipkin related configuration
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web

#Spring Cloud Open Feign related configuration
feign:
# circuitbreaker:
    #To use Spring Cloud Circuit Breaker instead of Hystrix, which should be required in the classpath
#   enabled: true
  hystrix:
    enabled: false
  client:
    config:
      default:
        #Spring cloud open feign connect and read timeout details along with log level
        connectTimeout: 12000
        readTimeout: 12000
        loggerLevel: basic

#Spring Kafka related configuration
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5


