feign:
#  circuitbreaker:
#    enabled: true #To use Spring Cloud Circuit Breaker which should be added in the classpath instead of Hystrix
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000
        loggerLevel: basic

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false #To use Spring Cloud Load Balancer which should be added in the classpath instead of Ribbon

