spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - x-requested-with
              - authorization
              - Content-Type
              - Content-Length
              - Authorization
              - credential
              - X-XSRF-TOKEN
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            maxAge: 7200
      discovery:
        locator:
          enabled: true
      routes:
        - id: bookstore-product-service
          uri: lb://bookstore-product-service
          predicates:
            - Path=/bookstore-product/**
          filters:
            - RewritePath=/bookstore-product/(?<path>.*), /$\{path}
            - name: Retry
        - id: bookstore-cart-service
          uri: lb://bookstore-cart-service
          predicates:
            - Path=/bookstore-cart/**
          filters:
            - RewritePath=/bookstore-cart/(?<path>.*), /$\{path}
            - name: Retry
        - id: bookstore-address-service
          uri: lb://bookstore-address-service
          predicates:
            - Path=/bookstore-address/**
          filters:
            - RewritePath=/bookstore-address/(?<path>.*), /$\{path}
            - name: Retry
        - id: bookstore-payment-service
          uri: lb://bookstore-payment-service
          predicates:
            - Path=/bookstore-payment/**
          filters:
            - RewritePath=/bookstore-payment/(?<path>.*), /$\{path}
            - name: Retry
        - id: bookstore-order-service
          uri: lb://bookstore-order-service
          predicates:
            - Path=/bookstore-order/**
          filters:
            - RewritePath=/bookstore-order/(?<path>.*), /$\{path}
            - name: Retry
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
            - name: Retry
      httpclient:
        connect-timeout: 50000
        response-timeout: 5s

logging:
  level:
    com.learning.bookstore.*: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, gateway
  endpoint:
    health:
      show-details: always

---

spring:
  profiles: local_zone1
  cloud:
    consul:
      discovery:
        instanceZone: zone1
        register: false
        registerHealthCheck: false
        tags: zone=zone1
server:
  port: ${PORT:8080}

---

spring:
  profiles: local_zone2
  cloud:
    consul:
      discovery:
        instanceZone: zone2
        register: false
        registerHealthCheck: false
        tags: zone=zone2
server:
  port: ${PORT:9080}

---

spring:
  profiles: docker
  cloud:
    consul:
      discovery:
        instanceZone: zone2
        register: false
        registerHealthCheck: false
        tags: zone=zone2
server:
  port: ${PORT:8080}