create table Product (
    id varchar(255) not null,
    name varchar(255) not null,
    description varchar(255),
    price double not null,
    available_count integer not null,
    image_id varchar(255),
    product_category_id varchar(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255) not null,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by varchar(255) not null,
    primary key (id)
);

create table Product_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    available_count integer,
    description varchar(255),
    image_id varchar(255),
    name varchar(255),
    price double,
    product_category_id varchar(255),
    primary key (id, REV)
);

create table Product_Category (
    id varchar(255) not null,
    name varchar(255) not null,
    description varchar(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255) not null,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by varchar(255) not null,
    primary key (id)
);

create table Product_Category_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    description varchar(255),
    name varchar(255),
    primary key (id, REV)
);

create table Product_Review (
    id varchar(255) not null,
    user_id varchar(255),
    rating integer not null,
    message varchar(1000),
    product_id varchar(255) not null,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by varchar(255) not null,
    last_modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modified_by varchar(255) not null,
    primary key (id)
);

create table Product_Review_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    message varchar(255),
    rating integer,
    user_id varchar(255),
    product_id varchar(255),
    primary key (id, REV)
);

create table REVINFO (
    REV integer generated by default as identity,
    REVTSTMP bigint,
    primary key (REV)
);

alter table Product
    add constraint FKProductToProductCategory
    foreign key (product_category_id)
    references Product_Category(id);

alter table Product_Review
    add constraint FKProductReviewToProduct
    foreign key (product_id)
    references Product(id);

alter table Product_AUD
   add constraint FKProductToProductAUD
   foreign key (REV)
   references REVINFO;

alter table Product_Category_AUD
   add constraint FKProductCategoryToProductCategoryAUD
   foreign key (REV)
   references REVINFO;

alter table Product_Review_AUD
       add constraint FKProductReviewToProductReviewAUD
       foreign key (REV)
       references REVINFO