create table Order_Item (
    id varchar(255) not null,
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    order_extended_price double not null,
    order_item_price double not null,
    product_id varchar(255) not null,
    quantity integer not null,
    order_id varchar(255),
    primary key (id)
);

create table Order_Item_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    order_extended_price double,
    order_item_price double,
    product_id varchar(255),
    quantity integer,
    order_id varchar(255),
    primary key (id, REV)
);

create table REVINFO (
    REV integer generated by default as identity,
    REVTSTMP bigint,
    primary key (REV)
);

create table User_Order (
    id varchar(255) not null,
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    billing_address_id varchar(255) not null,
    delivered_date timestamp not null,
    is_delivered boolean,
    is_paid boolean,
    payment_date timestamp not null,
    payment_id varchar(255),
    payment_method_id varchar(255) not null,
    payment_receipt_url varchar(255),
    shipping_address_id varchar(255) not null,
    shipping_price double not null,
    tax_price double not null,
    total_item_price double not null,
    total_order_price double not null,
    user_mail varchar(255) not null,
    primary key (id)
);

create table User_Order_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    billing_address_id varchar(255),
    delivered_date timestamp,
    is_delivered boolean,
    is_paid boolean,
    payment_date timestamp,
    payment_id varchar(255),
    payment_method_id varchar(255),
    payment_receipt_url varchar(255),
    shipping_address_id varchar(255),
    shipping_price double,
    tax_price double,
    total_item_price double,
    total_order_price double,
    user_mail varchar(255),
    primary key (id, REV)
);

alter table Order_Item
   add constraint FKhjsfxmnbwx4orbl77oqu1gd4r
   foreign key (order_id)
   references User_Order;

alter table Order_Item_AUD
   add constraint FK37owcxq33s9bj9n8daurpn7y
   foreign key (REV)
   references REVINFO;

alter table User_Order_AUD
   add constraint FKm5e0qxcf6b5wnqbb6ukmubeyw
   foreign key (REV)
   references REVINFO;