create table Cart (
    id varchar(255) not null,
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    total_price double not null,
    user_email varchar(255) not null,
    primary key (id)
);

create table Cart_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    total_price double,
    user_email varchar(255),
    primary key (id, REV)
);

create table Cart_Item (
    id varchar(255) not null,
    created_by varchar(255),
    created_date timestamp,
    last_modified_by varchar(255),
    last_modified_date timestamp,
    extended_price double,
    price double,
    product_id varchar(255),
    quantity integer,
    cart_id varchar(255),
    primary key (id)
);

create table Cart_Item_AUD (
    id varchar(255) not null,
    REV integer not null,
    REVTYPE tinyint,
    extended_price double,
    price double,
    product_id varchar(255),
    quantity integer,
    cart_id varchar(255),
    primary key (id, REV)
);

create table REVINFO (
    REV integer generated by default as identity,
    REVTSTMP bigint,
    primary key (REV)
);

alter table Cart
       add constraint UK_c0dw7wbtk30o5qyw9ssht42w2 unique (user_email);

alter table Cart_AUD
       add constraint FKe7kv1utft06jgmi1ywoy9ibls
       foreign key (REV)
       references REVINFO;

alter table Cart_Item
       add constraint FK9hehdx6004q7mv9oeh40ud417
       foreign key (cart_id)
       references Cart;

alter table Cart_Item_AUD
       add constraint FK7u293xjts0id5q4iotitcbcwt
       foreign key (REV)
       references REVINFO;