scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'consul'
    metrics_path: '/actuator/metrics'
    consul_sd_configs:
      - server: 'consul-1:8500'
        services: []
rule_files:
  - './rules.yml'
alerting:
   alertmanagers:
     - static_configs: 
         - targets:
             - alertmanager:9093 
    