groups:
- name: RateOfRequest
  rules:
  - alert: RequestRate
    expr:  rate(http_server_requests_seconds_count{uri="/v1/products"}[2m]) > 0
    for: 1m
    labels:
      severity: high
    annotations:
      summary: Application stopped receiving requests